// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Data;
using CodeGenerator;
using System.Reflection;
using System.Reflection.Emit;


namespace DataMapperTest
{
	/// <summary>
	///This is a test class for CodeGenerator.DataMapper and is intended
	///to contain all CodeGenerator.DataMapper Unit Tests
	///</summary>
	[TestClass]
	public class DataMapperTest
	{
		private DataTable _DateTable = new DataTable();
		private DateTime _CurrentDate;

		private TestContext testContextInstance;

		/// <summary>
		///Gets or sets the test context which provides
		///information about and functionality for the current test run.
		///</summary>
		public TestContext TestContext
		{
			get
			{
				return testContextInstance;
			}
			set
			{
				testContextInstance = value;
			}
		}
		#region Additional test attributes
		// 
		//You can use the following additional attributes as you write your tests:
		//
		//Use ClassInitialize to run code before running the first test in the class
		//
		//[ClassInitialize()]
		//public static void MyClassInitialize(TestContext testContext)
		//{
		//}
		//
		//Use ClassCleanup to run code after all tests in a class have run
		//
		//[ClassCleanup()]
		//public static void MyClassCleanup()
		//{
		//}
		//
		//Use TestInitialize to run code before running each test
		//
		[TestInitialize]
		public void MyTestInitialize()
		{
			DataSet dsTest = new DataSet();

			_DateTable = new DataTable();
			_DateTable.Columns.Add(new DataColumn("Field1", typeof(int)));
			_DateTable.Columns.Add(new DataColumn("Field2", typeof(string)));
			_DateTable.Columns.Add(new DataColumn("Field3", typeof(DateTime)));
			_DateTable.Columns.Add(new DataColumn("ParentId", typeof(int)));

			_DateTable.Rows.Add(72, "Hey!", _CurrentDate = DateTime.Now, 1);
			_DateTable.Rows.Add(34, "Twice", DateTime.MaxValue, 2);
			_DateTable.Rows.Add(DBNull.Value, DBNull.Value, DBNull.Value, DBNull.Value);

			dsTest.Tables.Add(_DateTable);

			DataTable childTable = new DataTable();
			childTable.Columns.Add(new DataColumn("Field1", typeof(int)));
			childTable.Columns.Add(new DataColumn("Field2", typeof(string)));
			childTable.Columns.Add(new DataColumn("Field3", typeof(DateTime)));
			childTable.Columns.Add(new DataColumn("ParentId", typeof(int)));

			childTable.Rows.Add(2, "Child 1", DateTime.Now, 1);
			childTable.Rows.Add(3, "Child 2", DateTime.MaxValue, 1);
			childTable.Rows.Add(4, "Child 3", DateTime.MaxValue, 2);
			childTable.Rows.Add(DBNull.Value, DBNull.Value, DBNull.Value, DBNull.Value);

			dsTest.Tables.Add(childTable);
			dsTest.Relations.Add("Relation1",
				_DateTable.Columns["ParentId"],
				childTable.Columns["ParentId"],
				false);
		}

		//Use TestCleanup to run code after each test has run
		//
		//[TestCleanup()]
		//public void MyTestCleanup()
		//{
		//}
		//
		#endregion

		[TestMethod]
		public void PerformanseTest()
		{
			int rowCount = 100000;

			DataTable dtPerfTest = new DataTable();
			dtPerfTest.Columns.Add(new DataColumn("Field1", typeof(int)));
			dtPerfTest.Columns.Add(new DataColumn("Field2", typeof(string)));
			dtPerfTest.Columns.Add(new DataColumn("Field3", typeof(DateTime)));

			for (int i = 0; i < rowCount; i++)
				dtPerfTest.Rows.Add(i, i.ToString(), DateTime.Now);

			List<TesterAll> tester = new List<TesterAll>(100000);

			DateTime dtStart = DateTime.Now;
			DataMapper.Default.FillObjectList<TesterAll>(tester, dtPerfTest.Rows);
			TimeSpan span = DateTime.Now - dtStart;

			testContextInstance.WriteLine("Time for creation of " + rowCount + " objects is: " + span);
			testContextInstance.WriteLine("Time for creation of one object is: " + new TimeSpan(span.Ticks / rowCount));
		}

		[TestMethod]
		public void FillObjectTest_NullableProp()
		{
			TesterNullableProp tester = new TesterNullableProp();
			DataMapper.Default.ClearCache();
			DataMapper.Default.SetConfig(null);
			DataMapper.Default.FillObject(_DateTable.Rows[0], tester, 0);

			if (tester.NullableProp != _CurrentDate)
				Assert.Fail("FillObjectTest_NullableProp fails.");

			DataMapper.Default.FillObject(_DateTable.Rows[2], tester, 0);

			if (tester.NullableProp != null)
				Assert.Fail("FillObjectTest_NullableProp with DBNull fails.");
		}

		[TestMethod]
		public void FillObjectTest_NullablePropNI()
		{
			TesterNullablePropNI tester = new TesterNullablePropNI();
			DataMapper.Default.ClearCache();
			DataMapper.Default.SetConfig(null);
			DataMapper.Default.FillObject(_DateTable.Rows[0], tester, 0);

			if (tester.NullableProp != true)
				Assert.Fail("FillObjectTest_NullablePropNI fails.");

			DataMapper.Default.FillObject(_DateTable.Rows[2], tester, 0);

			if (tester.NullableProp != null)
				Assert.Fail("FillObjectTest_NullablePropNI with DBNull fails.");
		}

		[TestMethod]
		public void FillObjectTest_ValueProp()
		{
			TesterValueProp tester = new TesterValueProp();
			DataMapper.Default.ClearCache();
			DataMapper.Default.SetConfig(null);
			DataMapper.Default.FillObject(_DateTable.Rows[0], tester, 0);

			if (tester.ValueProp != 72)
				Assert.Fail("FillObjectTest_ValueProp fails.");

			DataMapper.Default.FillObject(_DateTable.Rows[2], tester, 0);

			if (tester.ValueProp != default(int))
				Assert.Fail("FillObjectTest_ValueProp with DBNull fails.");
		}

		[TestMethod]
		public void FillObjectTest_ValuePropNI()
		{
			TesterValuePropNI tester = new TesterValuePropNI();
			DataMapper.Default.ClearCache();
			DataMapper.Default.SetConfig(null);
			DataMapper.Default.FillObject(_DateTable.Rows[0], tester, 0);

			if (tester.ValueProp != true)
				Assert.Fail("FillObjectTest_ValuePropNI fails.");

			DataMapper.Default.FillObject(_DateTable.Rows[2], tester, 0);

			if (tester.ValueProp != default(bool))
				Assert.Fail("FillObjectTest_ValuePropNI with DBNull fails.");
		}

		[TestMethod]
		public void FillObjectTest_RefProp()
		{
			TesterRefProp tester = new TesterRefProp();
			DataMapper.Default.ClearCache();
			DataMapper.Default.SetConfig(null);
			DataMapper.Default.FillObject(_DateTable.Rows[0], tester, 0);

			if (tester.RefProp != "Hey!")
				Assert.Fail("FillObjectTest_RefProp fails.");

			DataMapper.Default.FillObject(_DateTable.Rows[2], tester, 0);

			if (tester.RefProp != null)
				Assert.Fail("FillObjectTest_RefProp with DBNull fails.");
		}

		[TestMethod]
		public void FillObjectTest_StructProp()
		{
			TesterStructProp tester = new TesterStructProp();
			DataMapper.Default.ClearCache();
			DataMapper.Default.SetConfig(null);
			DataMapper.Default.FillObject(_DateTable.Rows[0], tester, 0);

			if (tester.StructProp != _CurrentDate)
				Assert.Fail("FillObjectTest_StructProp fails.");

			DataMapper.Default.FillObject(_DateTable.Rows[2], tester, 0);

			if (tester.StructProp != default(DateTime))
				Assert.Fail("FillObjectTest_StructProp with DBNull fails.");
		}

		[TestMethod]
		public void FillObjectTest()
		{
			TesterAll tester = new TesterAll();

			DataMapper.Default.FillObject(_DateTable.Rows[0], tester, 0);

			if (tester.ValueProp != 72 ||
				 tester.ValuePropNI != true ||
				 tester.RefProp != "Hey!" ||
				 tester.StructProp != _CurrentDate ||
				 tester.NullableProp != _CurrentDate ||
				 tester.NullablePropBool != true
				)
				Assert.Fail("FillObjectTest fails.");

			DataMapper.Default.FillObject(_DateTable.Rows[2], tester, 0);

			if (tester.ValueProp != default(int) ||
				 tester.ValuePropNI != default(bool) ||
				 tester.RefProp != null ||
				 tester.StructProp != default(DateTime) ||
				 tester.NullableProp != null ||
				 tester.NullablePropBool != null
				)
				Assert.Fail("FillObjectTest with DBNull fails.");
		}

		[TestMethod]
		public void FillObjectTestXML()
		{
			TesterAll tester = new TesterAll();

			DataMapper.Default.ClearCache();
			DataMapper.Default.SetConfig(@"..\..\..\CodeGenerator\data.mapping");
			DataMapper.Default.FillObject(_DateTable.Rows[0], tester, 0);

			if (tester.ValueProp != 72 ||
				 tester.ValuePropNI != true ||
				 tester.RefProp != "Hey!" ||
				 tester.StructProp != _CurrentDate ||
				 tester.NullableProp != _CurrentDate ||
				 tester.NullablePropBool != true
				)
				Assert.Fail("FillObjectTest fails.");

			DataMapper.Default.FillObject(_DateTable.Rows[2], tester, 0);

			if (tester.ValueProp != default(int) ||
				 tester.ValuePropNI != default(bool) ||
				 tester.RefProp != null ||
				 tester.StructProp != default(DateTime) ||
				 tester.NullableProp != null ||
				 tester.NullablePropBool != null
				)
				Assert.Fail("FillObjectTest with DBNull fails.");
		}
	}
}
